version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file: .env
    command: python backend.py

  bot:
    build: ./bot
    volumes:
      - ./bot:/app
    env_file: .env
    command: python bot.py
